### ISSUE TITLE
php 8 is not supported

### ISSUE THREAD

**Issue by douglasjam** [CakeDC/oauth2-cognito#2]
Currently, the supported version is fixed on 7.0

    - cakedc/oauth2-cognito 1.0.0 requires php ^5.6 || ^7.0 -> your php version (8.0.1) does not satisfy that requirement.

 I'll create a MR for it

**Comment by douglasjam** [comment]
https://github.com/CakeDC/oauth2-cognito/pull/3

would be great if a new tag is released if it's allowed to be merged

**Comment by ajibarra** [comment]
Created tag 2.0.0
